### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by zhongheli** [reiinakano/scikit-plot#30]
Hi i tried to pip install skikit-plot but got the following error message:
Command "python setup.py egg_info" failed with error code 1.

Any suggestion?

Thanks very much.

Elena

**Comment by zhongheli** [comment]
Thank you I have resolved it by uninstall the scikit-learn and updated to the 018 version.

**Comment by zhongheli** [comment]
ImportError: cannot import name '_safe_split'

I have successfully installed scikit-plot
but can't import classifier_factory.

What version of Python and scikit learn does your scikit-plot work with?

Thank you.

**Comment by reiinakano** [comment]
Hi. It should work with scikit learn 0.18 and above. 

This is probably an issue with your scikit learn installation as in https://github.com/scikit-learn/scikit-learn/issues/7582
